#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# catsub - little substitutor
#
# Copyright (c) 2018-2026  Ramses van Zon
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

from __future__ import print_function
import sys
import re
import collections
import os
import string

escaped_percentage_sign=u"％"  # abusing unicode character to escape '%'

def reject_unicode_on_python2(value):
   if sys.version_info[0] < 3:
      try:
         if isinstance(value, unicode):
            value.encode('ascii')
         else:
            value.decode('ascii')
      except UnicodeError:
         print("catsub does not support unicode when used with python version < 3.", file=sys.stderr)
         sys.exit(1)

def print_help():
   """print help message for the catsub command"""
   
   print(r"""
   catsub - substitutes every value for each variable 
            in each word of a template file.

   Usage:

     catsub [FLAGS] [TEMPLATEFILES] [%VARNAME VAL VAL ... | %@file:VARFILE]*

   where:

     TEMPLATEFILES  Name(s) of file(s) containg the template with
                    variables of the from %VARNAME; If no file name
                    is given, or the name is '-', catsub will read
                    from standard input;
     %VARNAME       Variable name to substitute;
     VAL VAL ...    Values to substitute for the variable. A VAL may
                    also be given as @file:PATH, in which case each line
                    in PATH is appended as one substitution value.
     %@file:VARFILE Import "%VARNAME VAL ..." expresssions from file VARFILE. 

     FLAGS:

       -s          Print statistics to stderr on resolved/nresolved variables.
       -u          Escaped percentage in template are returned unescaped;
       -E          Split whitespace-separated values imported with %@file:PATH;
       -dSTR       Use STR to divide multiple substituted values
       -D          Use newline to divide multiple substituted values
       -h|--help   Show this help page and exit.

   Notes: 

   - The names of the template files may not start with a percent sign.  

   - All variables must start with a percent sign and cannot contain
     whitespace.

   - Substituted values cannot start with a percent sign.

   - Values may be loaded from a file with @file:PATH; each line in the
     file is treated as one substitution value.

   - @file: sources are restricted to the current working directory,
     one of the (sub) directories in which the template files reside,
     or a user-owned /tmp or /dev/shm file.

   - Substitution happens only once per variable, i.e., substituted
     values do not undergo subsequent substitutions.

   - When substituting several values, those values are separated by a
     space, by a newline if the -D argument was given, or by STR if
     the -dSTR argument was given.

   - When a variable has been given several values to substitute and
     the variable occurs in a substring of a word in the template,
     that word get repeated. E.g. "echo un%X | catsub %X kind tidy"
     gives "unkind untidy"

   - Substitution happens combinatorically within a word. E.g. a word
     "%X,%Y" in the template, when processed with "catsub %X a b %Y c d"
     becomes "a,c a,d b,c b,d". Combinatorics can be circumvented by
     quoting the replacement values, i.e.  "catsub %X 'a b' %Y 'c d'"
     gives "a b,c d".

   - Substitution uses the longest possible variable name. E.g. in
     "%HELLOWORLD", both %HELLO and %HELLOWORLD could be substituted
     if values for both are specified on the catsub command, but it is
     the longer %HELLOWORLD that gets used.
   
   - Percentage signs in the template can escape substitution by
     prepeding them with a slash, i.e., '\%'.  Every '\%' in the
     template will be remain a '\%' unless the -u argument is used in
     the catsub command, in which case, they are replaced by '%'.

   - The template cannot use the unicode character '％'.

   Examples:

     $ echo %HELLO %UNIVERSE | catsub %HELLO Hi %UNIVERSE world
     Hi world

     $ echo %HELLO %UNIVERSE > example.tmpl
     $ catsub example.tmpl %HELLO Greetings %UNIVERSE universe!
     Greetings universe!
""")

def is_allowed_path(path, allowed):
   """Check whether a path is inside an allowed directory.

   In addition to the list of paths in 'allowed', paths under 
   ``/tmp`` or ``/dev/shm`` are allowed if the path is owned 
   by the current user.

   Paths are resolved before comparison. 
   
   Args:
      path:   The path to check.
      allowed: Directories under which resolved paths are permitted.

   Returns:
      True if the path is permitted, otherwise False.
   """
   assert(isinstance(path,str))
   assert(isinstance(allowed,list))
   realpath = os.path.realpath(path)
   for allow in allowed:
      allow = os.path.realpath(allow)
      if realpath==allow or realpath.startswith(allow+os.sep):
         return True
   for trusted in ['/tmp', '/dev/shm']:
      trusted = os.path.realpath(trusted)
      if realpath == trusted or realpath.startswith(trusted + os.sep):
         try:
            if os.stat(path).st_uid == os.getuid():
               return True
         except OSError:
            return False
   return False


def import_variable_value_file(varvals, splitlines=False):
   r"""
   Process the varvals list and allow values to be imported from files with %@file:PATH.
   Return a new varvals list with the %@file:PATH replaced by the contents of the file.
   """
   newvarvals = []
   lastargwasfile = False
   for arg in varvals:
      if arg.startswith('%@file:'):
         filename = arg[len('%@file:'):]
         if filename == '':
            print("catsub error - empty file name in '%@file:' value.", file=sys.stderr)
            sys.exit(1)
         if not is_allowed_path(filename, [os.getcwd()]):
            print("catsub error - file '" + filename + "' is outside the allowed directories.", file=sys.stderr)
            sys.exit(1)
         try:
            if not os.path.isfile(filename) or not os.access(filename, os.R_OK):
               raise IOError
            with open(filename,'r') as f:
               expectfirstvar = True
               for line in f:
                  value = line.rstrip('\r\n').lstrip()
                  if value == '':
                     continue
                  if expectfirstvar:
                     if not value.startswith('%'):
                        print("catsub error - first non-empty value in file '" + filename + "' must start with '%'.", file=sys.stderr)
                        sys.exit(1)
                     expectfirstvar = False
                  if splitlines:
                     newvarvals.extend(value.split())
                  else:
                     newvarvals.append(value)
               if expectfirstvar:
                  print("catsub error - file '" + filename + "' has no non-empty value.", file=sys.stderr)
                  sys.exit(1)
            lastargwasfile = True
         except (IOError, OSError):
            print("catsub error - could not open file '" + filename + "'.", file=sys.stderr)
            sys.exit(1)
      else:
         if len(arg) > 0 and arg[0] != '%' and lastargwasfile:
            print("catsub error - value '" + arg + "' after '%@file:' must start with '%'.", file=sys.stderr)
            sys.exit(1)
         newvarvals.append(arg)
         lastargwasfile = False
   return newvarvals


def substitute(templatefiles, varvals, unescape=False, reportstats=False, multisep=' '):
   """
   Process the template in templatefiles, given the argument list with
   variable definitions in varvals, possibly resolving escaped
   percentages intact.

   Arguments:

     templatefiles list of template files (where '-' means use stdin)
     varvals       list of variable names and values
     unescape:     if True, replace '\' followed by '%' in the templates by '%'
     reportstats:  if True, report unsubstituted variable names to stderr
     multisep:     string to separate multiple substituted values in a word
   """
   assert(isinstance(templatefiles,list))
   assert(isinstance(varvals,list))
   assert(isinstance(unescape,bool))
   assert(isinstance(reportstats,bool))
   assert(isinstance(multisep,str))
   # Collect allowed directories for @file:PATH values
   allowed = [os.getcwd()]
   for filename in templatefiles:
      if filename != '-' and filename != '':
         allowed.append(os.path.dirname(os.path.abspath(filename)))
   # Collect values for each variable from the command line.
   values  = collections.defaultdict(list)
   varname = '%DEFAULT'
   fileopt ='@file:'
   for arg in varvals:
      if len(arg)>0 and arg[0] == '%':
         if len(re.split(r'(\s+)', arg))==1:
            varname = arg
         else:
            print("catsub error - '"+arg+"' is not a valid variable name.")
            sys.exit(1)
      else:
         if arg.startswith(fileopt):
            filename = arg[len(fileopt):]
            try:
               if filename == '':
                  raise ValueError("catsub error - empty file name in '@file:' value.")
               if not is_allowed_path(filename, allowed):
                  raise ValueError("catsub error - file '" + filename + "' is outside the allowed directories.")
               if not os.path.isfile(filename) or not os.access(filename, os.R_OK):
                  raise IOError
               with open(filename,'r') as f:
                  for line in f:
                     # Ensure repeated substitution does not occur by escaping percentage signs
                     values[varname].append(line.rstrip('\r\n').replace('%',escaped_percentage_sign))
            except (IOError, OSError):
               print("catsub error - could not open file '" + filename + "'.", file=sys.stderr)
               sys.exit(1)
            except ValueError as e:
               print(str(e), file=sys.stderr)
               sys.exit(1)
         else:
            # Ensure repeated substitution does not occur by escaping percentage signs
            values[varname].append(arg.replace('%',escaped_percentage_sign))

   # if no files given, read from stdin, signaled by '-' as a filename
   if templatefiles == []:
      templatefiles = ['-']

   # keep track of variables in files that are not used
   if reportstats:
      allvars = set()
      usedvars = set()

   # process files   
   for filename in templatefiles:
      # open file or use standard in
      if filename == '-':
         f = sys.stdin
      else:
         try:
            f = open(filename, 'r')
         except:
            print("catsub error - could not open file '" + filename + "'.")
            sys.exit(1)
      # Process each line in the file and make substitutions in each word
      try:
         for line in f:
            reject_unicode_on_python2(line)
            if unescape:
               line = line.replace('\\%',escaped_percentage_sign)
            else:
               line = line.replace('\\%','\\'+escaped_percentage_sign)
            words = re.split(r'(\s+)', line)
            if reportstats:
               for word in words:
                  allvars |= set(word.split('%')[1:])
            for wordidx in range(len(words)):
               for varname in sorted(values.keys(),reverse=True):
                  if varname in words[wordidx]:
                     if reportstats:
                        usedvars.add(varname[1:])
                     replacements = []
                     for value in values[varname]:
                        replacements.append(words[wordidx].replace(varname,value))
                     words[wordidx] = multisep.join(replacements)
            replacedline = ''.join(words)
            # Undo escaping of percentage sign
            print(replacedline.replace(escaped_percentage_sign,'%'),end='')
      except:
         # Reading file or processing went wrong
         print("catsub error - could not process file '" + filename + "'.")
         sys.exit(1)
      if filename != '-':
         f.close()
   if reportstats:
      if len(values)!=len(usedvars):
         print("Unused variables:", file=sys.stderr)
         for word in values.keys():
            if not word[1:] in usedvars:
               print(word, file=sys.stderr)
      if len(usedvars)>0:
         print("Substituted variables:", file=sys.stderr)
         for word in usedvars:
            print('%'+word, file=sys.stderr)
      unsubstitutedvars = [var for var in allvars if not any(var.startswith(used) for used in usedvars) and not all(c in string.punctuation for c in var)]
      if len(unsubstitutedvars) > 0:
         print("Unsubstituted variables present in template:", file=sys.stderr)
         for word in unsubstitutedvars:
            print('%'+word, file=sys.stderr)

## Start of application ##

def main(argv):
   # Parse the arguments and pass to main
   for arg in argv:
      reject_unicode_on_python2(arg)
   filestart   = 1
   varstart    = 1
   unescape    = False
   splitlines  = False
   reportstats = False
   multisep    = ' '
   readopts  = True   # start reading option
   for i in range(1,len(argv)):
      if readopts and len(argv[i]) > 0 and argv[i][0] == '-':
         if argv[i] in ('--help','-h'):
            print_help()
            sys.exit(0)
         elif argv[i] == '-u':
            unescape=True
         elif argv[i] == '-E':
            splitlines = True
         elif argv[i] == '-s':
            reportstats = True
         elif argv[i] == '-D':
            multisep = '\n'
         elif argv[i][:2] == '-d':
            multisep = argv[i][2:]
         else:
            print("catsub error - unknown option '" + argv[i] + "'.")
            sys.exit(1)
         filestart = i + 1
         varstart  = i + 1
      else:
         optionson = False
         if len(argv[i]) > 0 and argv[i][0] == '%':
            varstart = i
            break
         else:
            varstart = i+1
   templatefiles = argv[filestart:varstart]
   subslist = import_variable_value_file(argv[varstart:], splitlines=splitlines)
   substitute(templatefiles, subslist, unescape=unescape, reportstats=reportstats,multisep=multisep)

if __name__ == "__main__":
   main(sys.argv)
